id = 2
title = "Cyber Academy: Modern Cryptography"
short = "Modern Cryptography" 
date = "Thursday 4/15 7:00PM-9:00PM PT"
description = """How can a Blowfish do encryption? Who are Ron, Adi, and Leonard? And what in the Diffe-Hellman is a key exchange? Learn all about symmetric and asymmetric encryption at Cyber Academy in Week 3!
"""
link = ""
slides = ""
