slug = "feedback"
title = "Feedback"
author = "Matt"
value = 5
description = "Please fill out the [feedback form](https://forms.gle/fur4Qoig4HLwXBkf9)."
tags = ["Intro"]
files = []
flag = "flag{f33dback_is_imp0rtant}"
enabled = true


