id = 3
title = "Cyber Academy: SQL/NoSQL Injection"
short = "SQL/NoSQL Injection" 
date = "Monday 10/18 6:00PM-8:00PM PT"
description = """Please DROP by and JOIN us for an event WHERE we will INSERT knowledge of SQL (and noSQL) injections into your personal database (your MIND). Better pay attention… There might not be a SQL!
"""
link = ""
slides = ""