id = 5
title = "Video Game Hacking"
short = "Video Game Hacking" 
date = "Thursday 5/6 7:00PM-9:00PM PT"
description = """Ever wanted to know how that guy snapped to your head in a shooter game right as you peeked or somehow knew what your next move was in a strategy game? If you want to learn how to make your own aimbot or learn more about how hackers can exploit multiplayer games through packet spoofing, then our Video Game Hacking workshop is for you! No prior experience necessary!
"""
link = ""
slides = ""
