slug = "postmaster"
title = "Postmaster"
author = "Matt"
value = 25
description = """Can you tell me what a [post](https://cyber-web-hacking-challenges.herokuapp.com/postmaster/) is used for?"""
tags = ["Intro"]
files = []
flag = "flag{you_might_call_yourself_POSTmaster_general}"
enabled = true