id = 1
title = "Cyber Academy: Classical Ciphers"
short = "Classical Ciphers" 
date = "Thursday 4/8 7:00PM-9:00PM PT"
description = """Who needs to hide things when you can just broadcast info to everyone and confuse all except for one with what your messages mean? Come learn about how people throughout history used a variety of ciphers to camouflage data in plain sight. I wonder what this last sentence says… Sterces yciuj yciuj laever ot seno erucesni eht kcarc ot woh laever osla ll'ew!
"""
link = ""
slides = ""
