id = 5
title = "CTF After Dark"
short = "CTF After Dark"
date = "11/15 6:00PM PT"
description = """Come to the first in person CTF After Dark this year! There will be food (first come first serve). This is the moment you’ve been training for. Get ready for some high octane, mind-boggling tests of hacking skill! Collaborate with your friends in our beginner friendly Capture The Flag (CTF) competition. Challenges will be targeted at the skills that you’ve learned from our Winter workshops. Top teams get bragging rights as well as prizes.

The challenges are open until Thursday 11/18 6:00 PM.

RSVP on the Facebook Event
"""
link = ""
slides = ""
