id = 4
title = "Cyber x Studio: Botting"
short = "Cyber x Studio: Botting" 
date = "Monday 10/25 6:00PM-8:00PM PT"
description = """ACM Cyber and Studio have come together to bring you a unique workshop about botting! Come back on a later date for more info!
"""
link = ""
slides = ""