id = 1
title = "ACM Cyber Fall General Meeting"
short = "Cyber Fall GM" 
date = "Monday 10/4 6:00PM-8:00PM PT"
description = """Thinking of building an aimbot to get you out of bronze? 🙈 Interested in learning about how hackers get their hands on private [UC] 👀 information? Then ACM Cyber is just for you!! 😍
Come out to Cyber's Fall General Meeting on Monday, October 4th, at Franz Hall 2258A to learn more about what we do, meet our officers, make friends, and participate in a fun ✨Disney-themed✨ cyber activity! No prior experience necessary!
"""
link = "https://docs.google.com/forms/d/e/1FAIpQLSf-IeHo_-cxk97Jp_Jb7-cyOm5v2Ih3h05Yi1UrLxizV1G0Fg/viewform?pli=1"
slides = ""