id = 7
title = "Psi Beta Rho"
short = "Psi Beta Rho" 
date = "Spring Quarter"
description = """ACM Cyber’s Psi Beta Rho is back and better than ever this spring quarter! Join a team with other bruins who love hacking and test your skills against some awesome ctfs! No prior experience is required, since teams will be competing in beginner-friendly ctfs with the guidance of cyber officers. CTFs for this quarter include angstrom ctf, cyber fasttrack, SDCTF, and more! Contact us for more details!
"""
link = ""
slides = ""
