slug = "feedback"
title = "Feedback"
author = "Henry"
value = 5
description = "Please fill out the [feedback form](https://forms.gle/mPELJYpHMnR1UrYV7)."
tags = ["SQLi"]
files = []
flag = "flag{oh_you_paid_attention!}"
enabled = true


