slug = "cinderella-cipher"
title = "Cinderella Cipher"
author = "jeffrey"
value = 10
description = """Seems like Aladdin is trying to say something as he's zigzagging in the sky on his magic carpet! Let's see what he has [to say](song_lyrics.txt). Enter the flag in the form \"flag{answer_here}\" """
tags = [ "cryptography" ]
files = [ "song_lyrics.txt" ]
flag = "flag{THR0UGHANENDLESSDIAM0NDSKY}"
enabled = true
