slug = "jones"
title = "Jones"
author = "Matt"
value = 15
description = """Indiana Jones sure has visited a lot of archaeological sites around the world. Take a look [here.](https://cyber-web-hacking-challenges.herokuapp.com/jones/)"""
tags = ["Intro"]
files = []
flag = "flag{beating_a_dead_horse}"
enabled = true