id = 3
title = "Advanced Reverse Engineering"
short = "Reverse Engineering" 
date = "Thursday 4/22 7:00PM-9:00PM PT"
description = """Want to go above and beyond your CS33 knowledge? Join the Cyber Academy in Week 4 to learn how to use disassemblers such as IDA Pro as well as advanced reverse engineering techniques!
"""
link = ""
slides = ""
