slug = "dns-records"
title = "DNS Records"
author = "defund"
value = 10
description = "There are some suspicious DNS records on acmcyber.com..."
tags = ["gm"]
files = []
flag = "flag{digging_for_records}"
enabled = true
