id = 4
title = "Cyber x Studio: Aimbot"
short = "Cyber x Studio: Aimbot" 
date = "Wednesday 11/10 7:00PM-9:00PM PT"
description = """ACM Cyber and Studio have come together to bring you a unique workshop about aimbot and cheat engine!
The location will be at Eng IV 67-124

RSVP on the Facebook Event
"""
link = ""
slides = ""
