slug = "stabbing"
title = "The Roman Empire" 
author = "Sophia"
value = 15
description = """We should totally just stab [Caesar](caesar.jpeg)! 
Please type your answer in all lowercase with underscores replacing spaces"""
tags = ["classical"]
files = ["caesar.jpeg"]
flag = "flag{ye_wzolnd_xgtrnlc_bujv_sxsb tcewsr}"
enabled = true
